title: Crypto Dossier
description: > # this means to ignore newlines until "baseurl:"
This website will host all of my videos and articles which i create for different blockchain porjects and speard their awareness.
permalink: ':title/'
baseurl: "/cryptodossier" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: "https://twitter.com/ultron91x" #if your site has a twitter account, enter it here

# Author Settings
author: ultron91x # add your name
author-img: david-freeman.jpg # add your photo
about-author: YouTuber | Blogger | Blockchain Follower | CryptoCurrency Lover. # add description
social-twitter: @ultron91x # my twitter handle
social-facebook: # add your Facebook handle
social-github: artemsheludko # add your Github handle
social-telegram: @ultron91x # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
